version: '3.8'

services:
  notification-service:
    image: notification-service:latest
    container_name: notification-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5001
    networks:
      - online-shopping-network

networks:
  online-shopping-network:
    driver: bridge
